version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13.3
    volumes:
      - edulive_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=edulive
      - POSTGRES_USER=mvzona
      - POSTGRES_PASSWORD=050596
    expose:
      - 5432

  redis:
    image: redis:6.2.5
    expose:
      - 6379

volumes:
  edulive_data: